# Generated by Django 5.1.1 on 2025-04-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsolution',
            name='extracted_solution_text',
            field=models.TextField(blank=True),
        ),
    ]
