# Generated by Django 5.1.1 on 2025-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_secret',
            field=models.CharField(default='3eaf4566e3af400f8809c857828ff590', max_length=64),
        ),
    ]
