# Generated by Django 5.1.1 on 2025-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_secret',
            field=models.CharField(default='941e36c79a9741ce9e79ca13c60b8f75', max_length=64),
        ),
    ]
