# Generated by Django 5.1.1 on 2025-04-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_secret',
            field=models.CharField(default='6bf5c986193e4c628ca98e3d2e2b9568', max_length=64),
        ),
    ]
