# Generated by Django 4.2.20 on 2025-04-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_secret',
            field=models.CharField(default='3f06c8e71cc548aea8777154eee4f498', max_length=64),
        ),
    ]
